import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "H1R4",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <link rel="icon" href="/icon/logoH1R4.svg" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
