"use client"

import axios from "axios";
import Linha from "./linhas";
import { useEffect, useState } from "react";
import "./termo.css"

export default function Termo(){
    
    const [palavra, alteraPalavra] = useState('')
    const [submit, alteraSubmit] = useState(0)
    const [linha, alteraLinha] = useState(0);
    const [palavra_certa, alteraPalavraCerta] = useState([]);

    let palavras = [
        {palavra: "ABATE"},
        {palavra: "ABRIR"},
        {palavra: "ACIMA"},
        {palavra: "ACTOR"},
        {palavra: "ADEUS"},
        {palavra: "AFINS"},
        {palavra: "AFORA"},
        {palavra: "ALGUM"},
        {palavra: "ALTOS"},
        {palavra: "AMADO"},
        {palavra: "AMIGA"},
        {palavra: "AMIGO"},
        {palavra: "ANUAL"},
        {palavra: "ANTES"},
        {palavra: "APITO"},
        {palavra: "ARADO"},
        {palavra: "AREIA"},
        {palavra: "AROMA"},
        {palavra: "ATIVO"},
        {palavra: "ATRIZ"},
        {palavra: "ATUAL"},
        {palavra: "AUDIO"},
        {palavra: "AULAS"},
        {palavra: "AVISO"},
        {palavra: "BALÃO"},
        {palavra: "BALDE"},
        {palavra: "BANCO"},
        {palavra: "BANDO"},
        {palavra: "BARCO"},
        {palavra: "BASTA"},
        {palavra: "BATER"},
        {palavra: "BEIRA"},
        {palavra: "BICHO"},
        {palavra: "BLOCO"},
        {palavra: "BOATO"},
        {palavra: "BOMBA"},
        {palavra: "BONDE"},
        {palavra: "BORDA"},
        {palavra: "BOSSA"},
        {palavra: "BOTAR"},
        {palavra: "BRASA"},
        {palavra: "BRAVA"},
        {palavra: "BREVE"},
        {palavra: "BRISA"},
        {palavra: "BROCA"},
        {palavra: "BUCAL"},
        {palavra: "BUCHA"},
        {palavra: "BUROU"},
        {palavra: "BURRA"},
        {palavra: "BURRO"},
        {palavra: "CABAL"},
        {palavra: "CABER"},
        {palavra: "CABOS"},
        {palavra: "CAÇAR"},
        {palavra: "CADET"},
        {palavra: "CAGAR"},
        {palavra: "CAÍDO"},
        {palavra: "CALAR"},
        {palavra: "CALDA"},
        {palavra: "CALMA"},
        {palavra: "CALOR"},
        {palavra: "CAMAR"},
        {palavra: "CAMPO"},
        {palavra: "CANAL"},
        {palavra: "CANAR"},
        {palavra: "CANOA"},
        {palavra: "CANTO"},
        {palavra: "CAPUZ"},
        {palavra: "CARRO"},
        {palavra: "CASAR"},
        {palavra: "CASOS"},
        {palavra: "CASTA"},
        {palavra: "CAVAR"},
        {palavra: "CEDER"},
        {palavra: "CENAS"},
        {palavra: "CENHO"},
        {palavra: "CESTA"},
        {palavra: "CHATA"},
        {palavra: "CHEFE"},
        {palavra: "CHULA"},
        {palavra: "CIFRA"},
        {palavra: "CIRCO"},
        {palavra: "CLARO"},
        {palavra: "CLIMA"},
        {palavra: "CLUBE"},
        {palavra: "COBRE"},
        {palavra: "COBRA"},
        {palavra: "COISA"},
        {palavra: "COLAR"},
        {palavra: "COLHA"},
        {palavra: "COMBO"},
        {palavra: "CONDE"},
        {palavra: "CORAR"},
        {palavra: "CORDA"},
        {palavra: "CORPO"},
        {palavra: "CORVO"},
        {palavra: "COSMO"},
        {palavra: "COXOS"},
        {palavra: "CREME"},
        {palavra: "CRIAN"},
        {palavra: "CRIME"},
        {palavra: "CRISE"},
        {palavra: "CUIDO"},
        {palavra: "CURAR"},
        {palavra: "CURTO"},
        {palavra: "CUTIS"},
        {palavra: "DADOS"},
        {palavra: "DANOS"},
        {palavra: "DANÇA"},
        {palavra: "DARDO"},
        {palavra: "DECOR"},
        {palavra: "DEIXO"},
        {palavra: "DENTE"},
        {palavra: "DEPOR"},
        {palavra: "DIETA"},
        {palavra: "DIZEM"},
        {palavra: "DOBRA"},
        {palavra: "DOCES"},
        {palavra: "DOGMA"},
        {palavra: "DOIDO"},
        {palavra: "DÓLAR"},
        {palavra: "DORAR"},
        {palavra: "DOTAR"},
        {palavra: "DROGA"},
        {palavra: "DUCHA"},
        {palavra: "DUETO"},
        {palavra: "DUNAS"},
        {palavra: "DUROU"},
        {palavra: "ÉBANO"},
        {palavra: "ÉDIPO"},
        {palavra: "ELEGE"},
        {palavra: "ELEVA"},
        {palavra: "ELITE"},
        {palavra: "ENTÃO"},
        {palavra: "ENVIO"},
        {palavra: "ERGUE"},
        {palavra: "ERVAS"},
        {palavra: "ESCAL"},
        {palavra: "ESQUI"},
        {palavra: "ESTAR"},
        {palavra: "EXAME"},
        {palavra: "EXATO"},
        {palavra: "EXIBE"},
        {palavra: "EXIGE"},
        {palavra: "EXITO"},
        {palavra: "EXTRA"},
        {palavra: "FACAS"},
        {palavra: "FACES"},
        {palavra: "FALTA"},
        {palavra: "FAROL"},
        {palavra: "FATOR"},
        {palavra: "FAVOR"},
        {palavra: "FEIAS"},
        {palavra: "FEIOS"},
        {palavra: "FEIRA"},
        {palavra: "FELIZ"},
        {palavra: "FEMUR"},
        {palavra: "FERAS"},
        {palavra: "FERIR"},
        {palavra: "FERRO"},
        {palavra: "FIADO"},
        {palavra: "FICAR"},
        {palavra: "FIDES"},
        {palavra: "FILME"},
        {palavra: "FINAS"},
        {palavra: "FINDA"},
        {palavra: "FINOS"},
        {palavra: "FITAS"},
        {palavra: "FIZEM"},
        {palavra: "FLOCO"},
        {palavra: "FLORA"},
        {palavra: "FLORE"},
        {palavra: "FLOTA"},
        {palavra: "FOBIA"},
        {palavra: "FOCAR"},
        {palavra: "FOGOS"},
        {palavra: "FOLGA"},
        {palavra: "FORME"},
        {palavra: "FORRO"},
        {palavra: "FRACA"},
        {palavra: "FRASE"},
        {palavra: "FREIO"},
        {palavra: "FRIAS"},
        {palavra: "FRIOS"},
        {palavra: "FUNDO"},
        {palavra: "FURAR"},
        {palavra: "FUROR"},
        {palavra: "FURTA"},
        {palavra: "GAITA"},
        {palavra: "GALHO"},
        {palavra: "GANHO"},
        {palavra: "GAROA"},
        {palavra: "GATOS"},
        {palavra: "GENRO"},
        {palavra: "GLIFO"},
        {palavra: "GLOBO"},
        {palavra: "GOLPE"},
        {palavra: "GRATA"},
        {palavra: "GRATO"},
        {palavra: "GRAVE"},
        {palavra: "GRIFO"},
        {palavra: "GRIPE"},
        {palavra: "GROSS"},
        {palavra: "GRUTA"},
        {palavra: "HARPA"},
        {palavra: "HASTE"},
        {palavra: "HAVER"},
        {palavra: "HINOS"},
        {palavra: "HORTA"},
        {palavra: "HUMOR"},
        {palavra: "HUMUS"},
        {palavra: "IDOSO"},
        {palavra: "IGUAL"},
        {palavra: "ILHAS"},
        {palavra: "IMUNE"},
        {palavra: "INFRA"},
        {palavra: "INTER"},
        {palavra: "IRADO"},
        {palavra: "IRENA"},
        {palavra: "IRINA"},
        {palavra: "IRMAO"},
        {palavra: "IRMOS"},
        {palavra: "IRRES"},
        {palavra: "IRRES"},
        {palavra: "ISCAS"},
        {palavra: "ISOLA"},
        {palavra: "ISTOÉ"},
        {palavra: "ITENS"},
        {palavra: "JARRO"},
        {palavra: "JOGOS"},
        {palavra: "JOVEM"},
        {palavra: "JUIZA"},
        {palavra: "JUIZO"},
        {palavra: "JUNTA"},
        {palavra: "JUNTO"},
        {palavra: "JURAR"},
        {palavra: "JUSTA"},
        {palavra: "JUSTO"},
        {palavra: "LADOS"},
        {palavra: "LAGOA"},
        {palavra: "LARGO"},
        {palavra: "LATAO"},
        {palavra: "LATAS"},
        {palavra: "LAXOS"},
        {palavra: "LEGAL"},
        {palavra: "LEIAM"},
        {palavra: "LENDO"},
        {palavra: "LEQUE"},
        {palavra: "LIDOS"},
        {palavra: "LIGAR"},
        {palavra: "LIMAO"},
        {palavra: "LIMAS"},
        {palavra: "LINHA"},
        {palavra: "LIRIO"},
        {palavra: "LISTA"},
        {palavra: "LIVRE"},
        {palavra: "LOBOS"},
        {palavra: "LOCAR"},
        {palavra: "LODOS"},
        {palavra: "LOGOS"},
        {palavra: "LONGE"},
        {palavra: "LOUCA"},
        {palavra: "LOUCO"},
        {palavra: "LOURA"},
        {palavra: "LOURD"},
        {palavra: "LUCRO"},
        {palavra: "LUGAR"},
        {palavra: "LUZES"},
        {palavra: "MAIOR"},
        {palavra: "MALAS"},
        {palavra: "MALHO"},
        {palavra: "MALTA"},
        {palavra: "MANCA"},
        {palavra: "MANDA"},
        {palavra: "MANOS"},
        {palavra: "MAPAS"},
        {palavra: "MARAS"},
        {palavra: "MARCA"},
        {palavra: "MARIA"},
        {palavra: "MARTE"},
        {palavra: "MATAR"},
        {palavra: "MEIAS"},
        {palavra: "MEIOS"},
        {palavra: "MENOR"},
        {palavra: "MENTE"},
        {palavra: "MENUS"},
        {palavra: "MESAS"},
        {palavra: "MESMO"},
        {palavra: "METAL"},
        {palavra: "METAS"},
        {palavra: "METRO"},
        {palavra: "MEUDE"},
        {palavra: "MEUSA"},
        {palavra: "MILHA"},
        {palavra: "MIOLO"},
        {palavra: "MIRAR"},
        {palavra: "MIRIM"},
        {palavra: "MISSA"},
        {palavra: "MITOS"},
        {palavra: "MODAL"},
        {palavra: "MODOS"},
        {palavra: "MOEDA"},
        {palavra: "MOITA"},
        {palavra: "MONAR"},
        {palavra: "MONTE"},
        {palavra: "MORAR"},
        {palavra: "MOROS"},
        {palavra: "MOSCA"},
        {palavra: "MOTEL"},
        {palavra: "MOVER"},
        {palavra: "MUDAR"},
        {palavra: "MUROS"},
        {palavra: "MUSAS"},
        {palavra: "NADAR"},
        {palavra: "NADJA"},
        {palavra: "NADOS"},
        {palavra: "NARIZ"},
        {palavra: "NASAL"},
        {palavra: "NAVAL"},
        {palavra: "NAVES"},
        {palavra: "NEBUL"},
        {palavra: "NEGRA"},
        {palavra: "NEGRO"},
        {palavra: "NENEM"},
        {palavra: "NETOS"},
        {palavra: "NINAR"},
        {palavra: "NOBRE"},
        {palavra: "NODOS"},
        {palavra: "NOMES"},
        {palavra: "NORTE"},
        {palavra: "NOTAS"},
        {palavra: "NUNCA"},
        {palavra: "NUVEM"},
        {palavra: "OBRAS"},
        {palavra: "OCIOS"},
        {palavra: "ODIAR"},
        {palavra: "OLHAR"},
        {palavra: "OMBRO"},
        {palavra: "ONÇAS"},
        {palavra: "OPALA"},
        {palavra: "OPERA"},
        {palavra: "OPINA"},
        {palavra: "ORCAR"},
        {palavra: "ORDEN"},
        {palavra: "ORELH"},
        {palavra: "ORGAN"},
        {palavra: "ORNAR"},
        {palavra: "OSCAR"},
        {palavra: "OSSOS"},
        {palavra: "OUVIR"},
        {palavra: "PAINS"},
        {palavra: "PAJEM"},
        {palavra: "PALAS"},
        {palavra: "PALAR"},
        {palavra: "PALHA"},
        {palavra: "PAMPA"},
        {palavra: "PANDA"},
        {palavra: "PANEL"},
        {palavra: "PAPEL"},
        {palavra: "PARAR"},
        {palavra: "PARDA"},
        {palavra: "PARDO"},
        {palavra: "PAREI"},
        {palavra: "PARIS"},
        {palavra: "PARRA"},
        {palavra: "PARTE"},
        {palavra: "PARTI"},
        {palavra: "PASSE"},
        {palavra: "PASTA"},
        {palavra: "PATAO"},
        {palavra: "PATAS"},
        {palavra: "PATOS"},
        {palavra: "PAULO"},
        {palavra: "PAUSA"},
        {palavra: "PECAR"},
        {palavra: "PEDAL"},
        {palavra: "PEDRA"},
        {palavra: "PEGOI"},
        {palavra: "PELAS"},
        {palavra: "PELOS"},
        {palavra: "PENTE"},
        {palavra: "PERAS"},
        {palavra: "PERCA"},
        {palavra: "PERCE"},
        {palavra: "PERDA"},
        {palavra: "PERFE"},
        {palavra: "PERNA"},
        {palavra: "PERTO"},
        {palavra: "PESCA"},
        {palavra: "PESOS"},
        {palavra: "PICOS"},
        {palavra: "PIEGA"},
        {palavra: "PINHA"},
        {palavra: "PIORA"},
        {palavra: "PIPAS"},
        {palavra: "PIRAR"},
        {palavra: "PITAS"},
        {palavra: "PLANU"},
        {palavra: "PLENO"},
        {palavra: "PLUGA"},
        {palavra: "PODER"},
        {palavra: "PODIA"},
        {palavra: "POEMA"},
        {palavra: "POETA"},
        {palavra: "PONDO"},
        {palavra: "PONTE"},
        {palavra: "PORTA"},
        {palavra: "POSAR"},
        {palavra: "POTES"},
        {palavra: "PRAÇA"},
        {palavra: "PRADO"},
        {palavra: "PREGA"},
        {palavra: "PRIMA"},
        {palavra: "PRIMO"},
        {palavra: "PROVA"},
        {palavra: "PUDOR"},
        {palavra: "PULAR"},
        {palavra: "PULOS"},
        {palavra: "PUNIR"},
        {palavra: "PUPAS"},
        {palavra: "QUAIS"},
        {palavra: "QUEDA"},
        {palavra: "QUEPE"},
        {palavra: "QUIOS"},
        {palavra: "RADAR"},
        {palavra: "RADIO"},
        {palavra: "RAIOS"},
        {palavra: "RAMAL"},
        {palavra: "RAMOS"},
        {palavra: "RANGI"},
        {palavra: "RAPAZ"},
        {palavra: "RAPEL"},
        {palavra: "RASTE"},
        {palavra: "RASUR"},
        {palavra: "RAZÃO"}
    ]
    
    

    let habilitado = [
        { linha1: "", linha2: "disable", linha3: "disable", linha4: "disable", linha5: "disable", linha6: "disable" },
        { linha1: "disable", linha2: "", linha3: "disable", linha4: "disable", linha5: "disable", linha6: "disable" },
        { linha1: "disable", linha2: "disable", linha3: "", linha4: "disable", linha5: "disable", linha6: "disable" },
        { linha1: "disable", linha2: "disable", linha3: "disable", linha4: "", linha5: "disable", linha6: "disable" },
        { linha1: "disable", linha2: "disable", linha3: "disable", linha4: "disable", linha5: "", linha6: "disable" },
        { linha1: "disable", linha2: "disable", linha3: "disable", linha4: "disable", linha5: "disable", linha6: "" },
        { linha1: "disable", linha2: "disable", linha3: "disable", linha4: "disable", linha5: "disable", linha6: "disable" }
        ]
    
    function mudaLinha(){
        alteraLinha(linha + 1);
        alteraPalavra("");
        
        if (linha == 5){
            alteraLinha(0);
        }
    }

    function getPalavra(){
        axios.get("/api/termo", {
            headers:{
                'Content-Type':'application/json'
            }
        })
        .then(
            function(response){
                alteraPalavraCerta( response.data )
                console.log(palavra_certa)
            }
        )
    }

    useEffect(()=> {
        getPalavra();
    },[]);

    return(
        palavra_certa.length > 0?
        <div id="termo">
            <div className="boxJogo">
                <h1 className="lblTermo">Termo</h1>
                <div className="boxTermo">
                    <Linha vetor = {palavras} palavra_certa = {palavra_certa} habilitado={habilitado[linha].linha1} alteraPalavra={alteraPalavra} alteraSubmit={alteraSubmit} mudaLinha = {mudaLinha} palavra = {palavra} submit = {submit} linha = {linha} alteraLinha={alteraLinha}/>
                    <Linha vetor = {palavras} palavra_certa = {palavra_certa} habilitado={habilitado[linha].linha2} alteraPalavra={alteraPalavra} alteraSubmit={alteraSubmit} mudaLinha = {mudaLinha} palavra = {palavra} submit = {submit} linha = {linha} alteraLinha={alteraLinha}/>
                    <Linha vetor = {palavras} palavra_certa = {palavra_certa} habilitado={habilitado[linha].linha3} alteraPalavra={alteraPalavra} alteraSubmit={alteraSubmit} mudaLinha = {mudaLinha} palavra = {palavra} submit = {submit} linha = {linha} alteraLinha={alteraLinha}/>
                    <Linha vetor = {palavras} palavra_certa = {palavra_certa} habilitado={habilitado[linha].linha4} alteraPalavra={alteraPalavra} alteraSubmit={alteraSubmit} mudaLinha = {mudaLinha} palavra = {palavra} submit = {submit} linha = {linha} alteraLinha={alteraLinha}/>
                    <Linha vetor = {palavras} palavra_certa = {palavra_certa} habilitado={habilitado[linha].linha5} alteraPalavra={alteraPalavra} alteraSubmit={alteraSubmit} mudaLinha = {mudaLinha} palavra = {palavra} submit = {submit} linha = {linha} alteraLinha={alteraLinha}/>
                    <Linha vetor = {palavras} palavra_certa = {palavra_certa} habilitado={habilitado[linha].linha6} alteraPalavra={alteraPalavra} alteraSubmit={alteraSubmit} mudaLinha = {mudaLinha} palavra = {palavra} submit = {submit} linha = {linha} alteraLinha={alteraLinha}/>
                </div>
            </div>
        </div>
        :
        <p>Carregando...</p>
    );
}